# Site
name: "Bartosz Mikulski"
title: "Bartosz Mikulski"
description: "Building trustworthy data pipelines because AI cannot learn from dirty data"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
# baseurl: http://gtom.info//BartoszMikulski
# baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Bartosz
    display_name: Bartosz
    author_image: 'assets/images/avatar.png'
    avatar: 'assets/images/avatar.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: mikulskibartosz@gmail.com
    web: https://www.google.com
    twitter: https://twitter.com/check
    description: "Building trustworthy data pipelines because AI cannot learn from dirty data"
  john:
    name: John
    display_name: John
    author_image: 'assets/images/avatar.png'
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: mikulskibartosz@gmail.com
    web: https://www.google.com
    twitter: https://twitter.com/check
    description: "Building trustworthy data pipelines because AI cannot learn from dirty data"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    

# Social links
facebook_username: "username"
twitter_username: "username"
instagram_username: "username"
linkedin_username: "username"

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
